### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by VladPerervenko** [statcompute/yap#1]
`> install.packages("C:/Users/User/Downloads/yap_0.1.0.tar.gz", repos = NULL, type = "source")
Installing package into ‘C:/Users/User/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Ошибка в getOctD(x, offset, len) :invalid octal digit
Warning in install.packages :
  installation of package ‘C:/Users/User/Downloads/yap_0.1.0.tar.gz’ had non-zero exit status`

**Comment by statcompute** [comment]
I just tested it on my win10 pro and debian without any problem and am wondering if the file you downloaded is corrupt. could you please check if the file is a valid tarball?

**Comment by VladPerervenko** [comment]
Files were damaged when copying. I don’t understand the reason. Now downloaded spare parts - master. Everything was normal. The question is being removed. I will try after the new year. Happy New Year. Good luck

**Comment by statcompute** [comment]
Thanks for testing the package. Please feel free to let me know what else I can assist.
